server:
  port: ${SERVER_PORT:8099}

spring:
  application:
    name: highloadhw2
  r2dbc:
    url: ${DATASOURCE_R2DBC_URL:r2dbc:postgresql://localhost:5432/test?currentSchema=user_service}
    username: ${DATASOURCE_USER_NAME:test}
    password: ${DATASOURCE_USER_PASSWORD:test}
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: user_service
    default-schema: user_service
    baseline-on-migrate: true
    create-schemas: true
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/test}
    user: ${DATASOURCE_USER_NAME:test}
    password: ${DATASOURCE_USER_PASSWORD:test}


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: highload-hw2
      environment: local

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: INFO

resilience4j:
  ratelimiter:
    instances:
      global-api-limit:
        limitForPeriod: 1000          # ← 1000 RPS
        limitRefreshPeriod: 1s
        timeoutDuration: 0ms          # если токенов нет — сразу 429
